version: '3'

services:
  webserver:
    build:
      context: ./docker/bin/${PHPVERSION}
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/config/vhosts:/etc/apache2/sites-enabled
      - ./docker/logs/apache2:/var/log/apache2
    depends_on:
      - database
      - redis
    networks:
      - symfony
  database:
    image: 'mysql:8.0'
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: "always"
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    networks:
      - symfony
  redis:
    image: 'redis:latest'
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"
    networks:
      - symfony

networks:
  symfony: